---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: reemf123/iss_tracker:1.0
        container_name: iss-tracker-app
        ports:
            - "5000:5000"
...